function mesu = pico_ioDialog(mesu)
%
% mesu = pico_ioDialog(mesu)
%
% Instantiates a Gui dialog that allows to adjust the parameters of a
% specific data acquisition.
%
% The parameter "mesu" is optionnal. If it is given, the fields of the the
% gui dialog are initiated to its values. If not, default values are taken.
%
% All the parameters are stored in the output structure "mesu".
%
% v0.01 - March, 9th 2020 - O. Doaré - olivier.doare@ensta-paris.fr

    default = pico_defaultMeasure() ;
    
    channelRangesChoices = {'10mV';'20mV';'50mV'; '100mV'; '200mV' ;...
                            '500mV'; '1V'; '2V'; '5V'; '10V'; '20V'} ;

    devicesChoices = {'ps2000', 'ps4000'} ;

    channelCouplingChoices = {'AC', 'DC'} ;
    
    plotDataChoices = {'ask', 'no', 'yes'} ;
   
    d = dialog('Position',[300 300 600 500],'Name','Picoscope 2000/4000 dialog');

    txt = uicontrol('Parent',d,...
       'Style','text',...
       'Position',[20 430 80 40],...
       'String','Device type');
   
    txt = uicontrol('Parent',d,...
       'Style','text',...
       'Position',[300 430 80 40],...
       'String','Plot data');
    
    txt = uicontrol('Parent',d,...
       'Style','text',...
       'Position',[50 10 210 40],...
       'String','Adjust parameters then click Go');

    txt = uicontrol('Parent',d,...
       'Style','text',...
       'Position',[20 410 360 20],...
       'String','File name');

    txt = uicontrol('Parent',d,...
       'Style','text',...
       'Position',[20 350 100 20],...
       'String','Frequency (Hz)');

    txt = uicontrol('Parent',d,...
       'Style','text',...
       'Position',[150 350 100 20],...
       'String','Duration (s)');

    txt = uicontrol('Parent',d,...
       'Style','text',...
       'Position',[280 350 100 20],...
       'String','Upsampling');

    txt = uicontrol('Parent',d,...
       'Style','text',...
       'Position',[50 280 100 20],...
       'String','Channel A');

    txt = uicontrol('Parent',d,...
       'Style','text',...
       'Position',[250 280 100 20],...
       'String','Channel B');
   
   device = uicontrol('Parent',d,...
       'Style','popup',...
       'Position',[110 450 100 20],...
       'String',devicesChoices,...
       'Callback',@device_callback);
   
   plotData = uicontrol('Parent',d,...
       'Style','popup',...
       'Position',[390 450 100 20],...
       'String',plotDataChoices,...
       'Callback',@plotData_callback);

    fileName = uicontrol('Parent',d,...
       'Style','edit',...
       'Position',[20 390 360 20],...
       'String','test.mat',...
       'Callback',@fileName_callback);

    samplingFrequency = uicontrol('Parent',d,...
       'Style','edit',...
       'Position',[20 330 100 20],...
       'String','44100',...
       'Callback',@samplingFrequency_callback);

    duration = uicontrol('Parent',d,...
       'Style','edit',...
       'Position',[150 330 100 20],...
       'String','2',...
       'Callback',@duration_callback);

    upSampling = uicontrol('Parent',d,...
       'Style','edit',...
       'Position',[280 330 100 20],...
       'String','16',...
       'Callback',@upSampling_callback);

    popupRangeA = uicontrol('Parent',d,...
       'Style','popup',...
       'Position',[50 240 100 25],...
       'String',channelRangesChoices,...
       'Callback',@popupRangeA_callback);

    popupRangeB = uicontrol('Parent',d,...
       'Style','popup',...
       'Position',[250 240 100 25],...
       'String',channelRangesChoices,...
       'Callback',@popupRangeB_callback);

    popupCouplingA = uicontrol('Parent',d,...
       'Style','popup',...
       'Position',[50 190 100 25],...
       'String',channelCouplingChoices,...
       'Callback',@popupCouplingA_callback);

    popupCouplingB = uicontrol('Parent',d,...
       'Style','popup',...
       'Position',[250 190 100 25],...
       'String',channelCouplingChoices,...
       'Callback',@popupCouplingB_callback);       

    chAInfo = uicontrol('Parent',d,...
       'Style','edit',...
       'Position',[20 150 150 20],...
       'String','chAInfo',...
       'Callback',@chAInfo_callback);

    chBInfo = uicontrol('Parent',d,...
       'Style','edit',...
       'Position',[220 150 150 20],...
       'String','chBInfo',...
       'Callback',@chBInfo_callback);

    chACal = uicontrol('Parent',d,...
       'Style','edit',...
       'Position',[20 90 70 20],...
       'String','1',...
       'Callback',@chACal_callback);

    chBCal = uicontrol('Parent',d,...
       'Style','edit',...
       'Position',[220 90 70 20],...
       'String','1',...
       'Callback',@chBCal_callback);

    chAUnit = uicontrol('Parent',d,...
       'Style','edit',...
       'Position',[100 90 70 20],...
       'String','V',...
       'Callback',@chAUnit_callback);

    chBUnit = uicontrol('Parent',d,...
       'Style','edit',...
       'Position',[300 90 70 20],...
       'String','V',...
       'Callback',@chBUnit_callback);

    txt = uicontrol('Parent',d,...
        'Style','text',...
        'Position',[20 110 70 20],...
        'String','Cal');

    txt = uicontrol('Parent',d,...
        'Style','text',...
        'Position',[220 110 70 20],...
        'String','Cal');

    txt = uicontrol('Parent',d,...
        'Style','text',...
        'Position',[100 110 70 20],...
        'String','Unit');

    txt = uicontrol('Parent',d,...
        'Style','text',...
        'Position',[300 110 70 20],...
        'String','Unit');

    btnGo = uicontrol('Parent',d,...
       'Position',[300 30 70 25],...
       'String','Go',...
       'Callback','delete(gcf)');

    %%%
    onOff = uicontrol('Parent',d,...
       'Style','checkBox',...
       'Position',[520 350 100 20],...
       'Value',0,...
       'Callback',@onOff_callback);

    amplitude = uicontrol('Parent',d,...
       'Style','edit',...
       'Position',[450 270 100 20],...
       'String','3',...
       'Callback',@amplitude_callback);

    startFrequency = uicontrol('Parent',d,...
       'Style','edit',...
       'Position',[450 200 100 20],...
       'String','20',...
       'Callback',@startFrequency_callback);

    endFrequency = uicontrol('Parent',d,...
       'Style','edit',...
       'Position',[450 130 100 20],...
       'String','20000',...
       'Callback',@endFrequency_callback);

    repetitions = uicontrol('Parent',d,...
       'Style','edit',...
       'Position',[450 60 100 20],...
       'String','3',...
       'Callback',@repetitions_callback);

    %%%

    txt = uicontrol('Parent',d,...
        'Style','text',...
        'Position',[430 400 100 20],...
        'String','Sig. gen.');

    txt = uicontrol('Parent',d,...
        'Style','text',...
        'Position',[450 350 50 20],...
        'String','On/Off');

    txt = uicontrol('Parent',d,...
        'Style','text',...
        'Position',[450 290 100 20],...
        'String','Amplitude');

    txt = uicontrol('Parent',d,...
        'Style','text',...
        'Position',[450 220 100 20],...
        'String','Min freq.');

    txt = uicontrol('Parent',d,...
        'Style','text',...
        'Position',[450 150 100 20],...
        'String','Max freq.');

    txt = uicontrol('Parent',d,...
        'Style','text',...
        'Position',[450 80 100 20],...
        'String','Repetitions');

    if ~exist('mesu')
       mesu = struct() ;
    end

    if isfield(mesu,'nChannels')==0
        mesu.nChannels = default.nChannels ;
    end
    
    if isfield(mesu,'saveFile')==0
        mesu.saveFile = default.saveFile ;
    end

    if isfield(mesu,'Fs')==0
        mesu.Fs = default.Fs ;
    end

    if isfield(mesu,'duration')==0
        mesu.duration = default.duration ;
    end

    if isfield(mesu,'upSample')==0
        mesu.upSample = default.upSample ;       
    end

    if isfield(mesu,'inRange')==0
        mesu.inRange = default.inRange ;       
    end        

    if isfield(mesu,'inCoupling')==0
        mesu.inCoupling = default.inCoupling ;       
    end    

    if isfield(mesu,'inDesc')==0
        mesu.inDesc = default.inDesc ;
    end

    if isfield(mesu,'inCal')==0
        mesu.inCal = default.inCal ;       
    end

    if isfield(mesu,'inUnit')==0
        mesu.inUnit = default.inUnit ;       
    end

    if isfield(mesu,'sg')==0
        mesu.sg = default.sg ;
    end

    if isfield(mesu,'sgType')==0
        mesu.sgType = default.sgType ;
    end
    
    if isfield(mesu,'sgAmplitude')==0
        mesu.sgAmplitude = default.sgAmplitude ;
    end

    if isfield(mesu,'sgStartFrequency')==0
        mesu.sgStartFrequency = default.sgStartFrequency ;
    end

    if isfield(mesu,'sgEndFrequency')==0
        mesu.sgEndFrequency = default.sgEndFrequency ;
    end

    if isfield(mesu,'sgRepetitions')==0
        mesu.sgRepetitions = default.sgRepetitions ;
    end
    
    if isfield(mesu,'displayLiveData')==0
        mesu.displayLiveData = default.displayLiveData ;
    end

    if isfield(mesu,'picoDev')==0
        mesu.picoDev = default.picoDev ;
    end

    set(chAInfo,'String',mesu.inDesc{1}) ;       
    set(chBInfo,'String',mesu.inDesc{2}) ;     
    set(fileName,'String',mesu.saveFile) ;
    set(samplingFrequency,'String',num2str(mesu.Fs)) ;
    set(duration,'String',num2str(mesu.duration)) ;
    set(upSampling,'String',num2str(mesu.upSample)) ;
    set(popupRangeA,'Value',mesu.inRange{1}+1) ;       
    set(popupRangeB,'Value',mesu.inRange{2}+1) ;       
    set(popupCouplingA,'Value',mesu.inCoupling{1}+1) ;       
    set(popupCouplingB,'Value',mesu.inCoupling{2}+1) ;
    set(chACal,'String',num2str(mesu.inCal(1))) ;
    set(chBCal,'String',num2str(mesu.inCal(2))) ;
    set(chAUnit,'String',num2str(mesu.inUnit{1})) ;
    set(chBUnit,'String',num2str(mesu.inUnit{2})) ;
    set(plotData,'Value',mesu.displayLiveData+2) ;
    index = find(strcmp(devicesChoices, mesu.picoDev)) ;
    set(device,'Value',index) ;

    %%%
    set(onOff,'Value',mesu.sg) ;   
    set(amplitude,'String',num2str(mesu.sgAmplitude)) ;
    set(startFrequency,'String',num2str(mesu.sgStartFrequency)) ;
    set(endFrequency,'String',num2str(mesu.sgEndFrequency)) ;
    set(repetitions,'String',num2str(mesu.sgRepetitions)) ; 
    
    %%%

    mesu.nChannels = 2 ;
   
    % Wait for d to close before running to completion
    uiwait(d);
    
    function device_callback(popup,event)
      mesu.picoDev = popup.String{popup.Value}
    end

    function plotData_callback(popup,event)
      mesu.displayLiveData = popup.Value-2
    end

    function popupRangeA_callback(popup,event)
      mesu.inRange{1} = popup.Value-1
    end

    function popupRangeB_callback(popup,event)
      mesu.inRange{2} = popup.Value-1
    end

    function popupCouplingA_callback(popup,event)
      mesu.inCoupling{1} = popup.Value-1
    end

    function popupCouplingB_callback(popup,event)
      mesu.inCoupling{2} = popup.Value-1
    end

    function chAInfo_callback(edit,event)
        mesu.inDesc{1} = edit.String
    end

    function chBInfo_callback(edit,event)
        mesu.inDesc{2} = edit.String
    end

    function fileName_callback(edit,event)
        mesu.saveFile = edit.String
    end

    function samplingFrequency_callback(edit,event)
        mesu.Fs = str2num(edit.String)
    end

    function duration_callback(edit,event)
        mesu.duration = str2num(edit.String)
    end

    function upSampling_callback(edit,event)
        mesu.upSample = str2num(edit.String)
    end

    function chACal_callback(edit,event)
        mesu.inCal(1) = str2num(edit.String)
    end

    function chBCal_callback(edit,event)
        mesu.inCal(2) = str2num(edit.String)
    end
    function chAUnit_callback(edit,event)
          mesu.inUnit{1} = edit.String
    end
    function chBUnit_callback(edit,event)
        mesu.inUnit{2} = edit.String
    end

    function onOff_callback(edit,event)
       mesu.sg = edit.Value
    end

    function amplitude_callback(edit,event)
       mesu.sgAmplitude = str2num(edit.String)
    end

    function startFrequency_callback(edit,event)
        mesu.sgStartFrequency = str2num(edit.String)
    end

    function endFrequency_callback(edit,event)
        mesu.sgEndFrequency = str2num(edit.String)
    end

    function repetitions_callback(edit,event)
        mesu.sgRepetitions = str2num(edit.String)
    end

end

